### ISSUE TITLE
[Bug]: Problème avec la liaison à la base de donnés

### ISSUE THREAD

**Issue by AlexiFon** [IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04#43]
### What happened?

Au lancement problème pour se connecter à la base de donnés.

### Version

0.2

### Relevant log output

```shell
Fatal error: Uncaught mysqli_sql_exception: Connection refused in /app/connexionBaseDeDonnees.php:16
Stack trace:
#0 /app/connexionBaseDeDonnees.php(16): mysqli->__construct('BaseDeDonnes', 'UserBd', Object(SensitiveParameterValue), 'Donnes')
#1 /app/connexionMQTT.php(18): InitBase()
#2 {main}
 thrown in /app/connexionBaseDeDonnees.php on line 16

**Comment by AlexiFon** [comment]
Problème réglé grace au changement en script python
